apiVersion: v2
name: excalidraw
description: Virtual whiteboard for sketching hand-drawn like diagrams
type: application
version: 0.6.9
keywords:
  - whiteboard
  - excalidraw
home: https://github.com/johanneskastl/excalidraw-helm-chart/tree/main/charts/excalidraw/
sources:
  - https://github.com/excalidraw/excalidraw
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update excalidraw digest to sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
