apiVersion: v2
name: excalidraw
description: Virtual whiteboard for sketching hand-drawn like diagrams
type: application
version: 0.6.8
keywords:
  - whiteboard
  - excalidraw
home: https://github.com/johanneskastl/excalidraw-helm-chart/tree/main/charts/excalidraw/
sources:
  - https://github.com/excalidraw/excalidraw
maintainers:
  - name: johanneskastl
    email: git@johannes-kastl.de
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update excalidraw digest to sha256:4542f30bea392b833822d0e7db4fa2220e6706ca962c082add2665159fa91758
